# Tensors are a specialized data structure that are very similar to arrays and matrices.
# 1.In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.
#2.Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data



In [ ]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
type(x_data)

torch.Tensor

# initializing  a tensor:
1. Direct Initialization.
2. Via a NumPy array.
3. Using another existing tensor.
4. Random initialization.

In [5]:
# Direct Initialization
direct_data = torch.tensor([[1,2], [2, 1]])
print(direct_data)

tensor([[1, 2],
        [2, 1]])


In [6]:
# NumPy init
arr = np.array([[1,2], [2,1]])
arr = torch.from_numpy(arr)
print(arr)

tensor([[1, 2],
        [2, 1]])


In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7712, 0.5851],
        [0.3359, 0.9420]]) 



In [ ]:
# Random Init
shape = (4,5,) # Tensor of 4x5
tensor_rand = torch.rand(shape)
tensor_1 = torch.ones(shape)
tensor_0 = torch.zeros(shape)

print('Random Tensor in 4x5 : \n\n', tensor_rand)
print('\nTensor of ones in 4x5 : \n\n', tensor_1)
print('\nTensor of zeros in 4x5 : \n\n', tensor_0)

Random Tensor in 4x5 : 

 tensor([[0.5348, 0.0809, 0.5792, 0.2718, 0.2203],
        [0.7247, 0.7594, 0.5925, 0.2026, 0.2746],
        [0.0442, 0.6652, 0.8973, 0.6584, 0.9205],
        [0.7065, 0.0698, 0.8376, 0.4871, 0.8880]])

Tensor of ones in 4x5 : 

 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Tensor of zeros in 4x5 : 

 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


## Tensor Attributes

Every tensor has attributes such as:

    1. Shape
    2. Datatype
    3. Device

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

1. Slicing
2. Indexing
3. Joining Tensors(concatination)
4. Arithmetic Operations of Tensors
5. Aggregation
6. In-place Operations

In [11]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [13]:
# Matrix Multiplication using Tensors
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [14]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [15]:
# Aggregation and Numerical Value
print(tensor.sum(), ' : ' ,tensor.sum().item())

tensor(12.)  :  12.0


In [16]:
# In-Place Operations

print(tensor.add_(5))

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [17]:
#tensor to numpy
t=torch.ones(5)
print(f"t:{t}")
n=t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


# NumPy array to Tensor

In [18]:
n=np.ones(5)
t=torch.from_numpy(n)
np.add(n,1,out=n)
print(f"t:{t}\nn:{n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]
